#
# Example Configuration File
#

# Default tests

list    10      # number of items in list
map     10      # -- ditto -- for map
tlv     10      # -- ditto -- for tag/length/value
fs      .       # directory to search for FS tests

# Advanced tests

booleans    true,0,no,yes,on,false
integers    91,19,61,94,36,4,97,5,11,3
decimals    7.3978863686,3.5744060420,1.3569795774,10.9705342605,3.2407552753,10.6308654973,5.7737904496,2.7558889448,8.0093142511,7.6826588739

# values for lists can be split over multiple lines if desired

strings     first
strings     2nd
strings     a couple,a,B,Cee
